# Workflow to build and publish documentation

name: Build and deploy spidar-sdk documentation

on:
  push:
  workflow_dispatch:

jobs:

  build:

    name: Build and deploy docs
    runs-on: ubuntu-latest
    
    steps:
          
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update -y 
          sudo apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended

      - name: Build Sphinx documentation as a pdf
        run : |
          cd docs/
          make latexpdf

      - name: Build Sphinx documentation html
        uses: ax3l/sphinx-action@newer-sphinx
        with:
          docs-folder: "docs/"

      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html


      - name: Upload pdf 
        uses: actions/upload-artifact@v1
        with:
          name: spidar-sdk
          path: docs/_build/latex/spidar-sdk.pdf

        