# Workflow to build documentation

name: Build documentation

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events 
  push:

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
          
      - name: Clone repo
        uses: actions/checkout@v2
