# Workflow to build documentation

name: Build documentation

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events 
  push:

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
          
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Build Sphinx documentation
        uses: ammaraskar/sphinx-action@35082eb35b69713fe335801c4d5846a4cc3c91ff
        with:
          docs-folder: "docs/"
