# Workflow to build and publish documentation

name: Build and deploy spidar-sdk documentation

on:
  push:
  workflow_dispatch:

jobs:

  build:

    name: Build and deploy docs
    runs-on: ubuntu-latest
    
    steps:
          
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Build Sphinx documentation as a pdf
        uses: ax3l/sphinx-action@31d7bf8fecdb2ef0315d87487bf6b2ab17869b4a
        with:
          docs-folder: "docs/"
          pre-build-command: "apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"
          build-command: "make latexpdf"

      - name: Build Sphinx documentation into html
        uses: ammaraskar/sphinx-action@35082eb35b69713fe335801c4d5846a4cc3c91ff
        with:
          docs-folder: "docs/"

      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html

      - name: Upload pdf 
        uses: actions/upload-artifact@v1
        with:
          name: spidar-sdk
          path: docs/_build/latex/spidarsdk.pdf
       
       # TODO: don't forget remove this when merging to main
      - name: Copy artifact to the Q drive.
        uses: benc-uk/workflow-dispatch@v1	
        with:	
         workflow: Copy to Q Drive
         repo: SensoftInc/build_utilities	
         token: ${{ secrets.TRACEY_CONTAINER_TOKEN }}	
         ref: master
         inputs: '{ "WORKFLOW_FILE_NAME": "build_docs.yml" , "Q_DRIVE_PATH": "/q/Depts/R&D/Active Projects/F0008 SPIDAR SDK NPI/docs_pdf" , "PACKAGE_REPO_NAME" : "SensoftInc/spidar-sdk" , "NAME_OF_ARTIFACT": "spidar-sdk"}' 


        
